version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "semiannually"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "semiannually"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "semiannually"
