name: Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
  # Allows the release workflow to run the tests before publishing
  workflow_call:

jobs:
  pytest_commit:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          version: latest

      - name: Install the project and its dependencies
        run: uv sync

      - name: Run prek
        run: uv run prek run --all-files

      - name: Run Pytest
        run: uv run pytest --cov=src --cov-report term ./tests
